package com.xptschool.parent.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEAN_HOT_GOOD".
*/
public class BeanHotGoodDao extends AbstractDao<BeanHotGood, Void> {

    public static final String TABLENAME = "BEAN_HOT_GOOD";

    /**
     * Properties of entity BeanHotGood.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "ID");
        public final static Property Url_pc_short = new Property(1, String.class, "url_pc_short", false, "URL_PC_SHORT");
        public final static Property Image = new Property(2, String.class, "image", false, "IMAGE");
    };


    public BeanHotGoodDao(DaoConfig config) {
        super(config);
    }
    
    public BeanHotGoodDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEAN_HOT_GOOD\" (" + //
                "\"ID\" TEXT," + // 0: id
                "\"URL_PC_SHORT\" TEXT," + // 1: url_pc_short
                "\"IMAGE\" TEXT);"); // 2: image
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEAN_HOT_GOOD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BeanHotGood entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String url_pc_short = entity.getUrl_pc_short();
        if (url_pc_short != null) {
            stmt.bindString(2, url_pc_short);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(3, image);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BeanHotGood entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String url_pc_short = entity.getUrl_pc_short();
        if (url_pc_short != null) {
            stmt.bindString(2, url_pc_short);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(3, image);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BeanHotGood readEntity(Cursor cursor, int offset) {
        BeanHotGood entity = new BeanHotGood( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url_pc_short
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // image
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BeanHotGood entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUrl_pc_short(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BeanHotGood entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BeanHotGood entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
