package com.shuhai.anfang.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTACT_TEACHER_FOR_TEACHER".
*/
public class ContactTeacherForTeacherDao extends AbstractDao<ContactTeacherForTeacher, Void> {

    public static final String TABLENAME = "CONTACT_TEACHER_FOR_TEACHER";

    /**
     * Properties of entity ContactTeacherForTeacher.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property School_name = new Property(0, String.class, "school_name", false, "SCHOOL_NAME");
        public final static Property Area_name = new Property(1, String.class, "area_name", false, "AREA_NAME");
    };


    public ContactTeacherForTeacherDao(DaoConfig config) {
        super(config);
    }
    
    public ContactTeacherForTeacherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTACT_TEACHER_FOR_TEACHER\" (" + //
                "\"SCHOOL_NAME\" TEXT," + // 0: school_name
                "\"AREA_NAME\" TEXT);"); // 1: area_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACT_TEACHER_FOR_TEACHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContactTeacherForTeacher entity) {
        stmt.clearBindings();
 
        String school_name = entity.getSchool_name();
        if (school_name != null) {
            stmt.bindString(1, school_name);
        }
 
        String area_name = entity.getArea_name();
        if (area_name != null) {
            stmt.bindString(2, area_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContactTeacherForTeacher entity) {
        stmt.clearBindings();
 
        String school_name = entity.getSchool_name();
        if (school_name != null) {
            stmt.bindString(1, school_name);
        }
 
        String area_name = entity.getArea_name();
        if (area_name != null) {
            stmt.bindString(2, area_name);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ContactTeacherForTeacher readEntity(Cursor cursor, int offset) {
        ContactTeacherForTeacher entity = new ContactTeacherForTeacher( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // school_name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // area_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContactTeacherForTeacher entity, int offset) {
        entity.setSchool_name(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setArea_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ContactTeacherForTeacher entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ContactTeacherForTeacher entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
