package com.shuhai.anfang.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shuhai.anfang.model.BeanBanner;
import com.shuhai.anfang.model.BeanClass;
import com.shuhai.anfang.model.BeanCourse;
import com.shuhai.anfang.model.BeanHomeCfg;
import com.shuhai.anfang.model.BeanHomeCfgChild;
import com.shuhai.anfang.model.BeanHotGood;
import com.shuhai.anfang.model.BeanLearningModule;
import com.shuhai.anfang.model.BeanParent;
import com.shuhai.anfang.model.BeanStudent;
import com.shuhai.anfang.model.BeanTeacher;
import com.shuhai.anfang.model.ContactParent;
import com.shuhai.anfang.model.ContactSchool;
import com.shuhai.anfang.model.ContactTeacher;

import com.shuhai.anfang.model.BeanBannerDao;
import com.shuhai.anfang.model.BeanClassDao;
import com.shuhai.anfang.model.BeanCourseDao;
import com.shuhai.anfang.model.BeanHomeCfgDao;
import com.shuhai.anfang.model.BeanHomeCfgChildDao;
import com.shuhai.anfang.model.BeanHotGoodDao;
import com.shuhai.anfang.model.BeanLearningModuleDao;
import com.shuhai.anfang.model.BeanParentDao;
import com.shuhai.anfang.model.BeanStudentDao;
import com.shuhai.anfang.model.BeanTeacherDao;
import com.shuhai.anfang.model.ContactParentDao;
import com.shuhai.anfang.model.ContactSchoolDao;
import com.shuhai.anfang.model.ContactTeacherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanBannerDaoConfig;
    private final DaoConfig beanClassDaoConfig;
    private final DaoConfig beanCourseDaoConfig;
    private final DaoConfig beanHomeCfgDaoConfig;
    private final DaoConfig beanHomeCfgChildDaoConfig;
    private final DaoConfig beanHotGoodDaoConfig;
    private final DaoConfig beanLearningModuleDaoConfig;
    private final DaoConfig beanParentDaoConfig;
    private final DaoConfig beanStudentDaoConfig;
    private final DaoConfig beanTeacherDaoConfig;
    private final DaoConfig contactParentDaoConfig;
    private final DaoConfig contactSchoolDaoConfig;
    private final DaoConfig contactTeacherDaoConfig;

    private final BeanBannerDao beanBannerDao;
    private final BeanClassDao beanClassDao;
    private final BeanCourseDao beanCourseDao;
    private final BeanHomeCfgDao beanHomeCfgDao;
    private final BeanHomeCfgChildDao beanHomeCfgChildDao;
    private final BeanHotGoodDao beanHotGoodDao;
    private final BeanLearningModuleDao beanLearningModuleDao;
    private final BeanParentDao beanParentDao;
    private final BeanStudentDao beanStudentDao;
    private final BeanTeacherDao beanTeacherDao;
    private final ContactParentDao contactParentDao;
    private final ContactSchoolDao contactSchoolDao;
    private final ContactTeacherDao contactTeacherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanBannerDaoConfig = daoConfigMap.get(BeanBannerDao.class).clone();
        beanBannerDaoConfig.initIdentityScope(type);

        beanClassDaoConfig = daoConfigMap.get(BeanClassDao.class).clone();
        beanClassDaoConfig.initIdentityScope(type);

        beanCourseDaoConfig = daoConfigMap.get(BeanCourseDao.class).clone();
        beanCourseDaoConfig.initIdentityScope(type);

        beanHomeCfgDaoConfig = daoConfigMap.get(BeanHomeCfgDao.class).clone();
        beanHomeCfgDaoConfig.initIdentityScope(type);

        beanHomeCfgChildDaoConfig = daoConfigMap.get(BeanHomeCfgChildDao.class).clone();
        beanHomeCfgChildDaoConfig.initIdentityScope(type);

        beanHotGoodDaoConfig = daoConfigMap.get(BeanHotGoodDao.class).clone();
        beanHotGoodDaoConfig.initIdentityScope(type);

        beanLearningModuleDaoConfig = daoConfigMap.get(BeanLearningModuleDao.class).clone();
        beanLearningModuleDaoConfig.initIdentityScope(type);

        beanParentDaoConfig = daoConfigMap.get(BeanParentDao.class).clone();
        beanParentDaoConfig.initIdentityScope(type);

        beanStudentDaoConfig = daoConfigMap.get(BeanStudentDao.class).clone();
        beanStudentDaoConfig.initIdentityScope(type);

        beanTeacherDaoConfig = daoConfigMap.get(BeanTeacherDao.class).clone();
        beanTeacherDaoConfig.initIdentityScope(type);

        contactParentDaoConfig = daoConfigMap.get(ContactParentDao.class).clone();
        contactParentDaoConfig.initIdentityScope(type);

        contactSchoolDaoConfig = daoConfigMap.get(ContactSchoolDao.class).clone();
        contactSchoolDaoConfig.initIdentityScope(type);

        contactTeacherDaoConfig = daoConfigMap.get(ContactTeacherDao.class).clone();
        contactTeacherDaoConfig.initIdentityScope(type);

        beanBannerDao = new BeanBannerDao(beanBannerDaoConfig, this);
        beanClassDao = new BeanClassDao(beanClassDaoConfig, this);
        beanCourseDao = new BeanCourseDao(beanCourseDaoConfig, this);
        beanHomeCfgDao = new BeanHomeCfgDao(beanHomeCfgDaoConfig, this);
        beanHomeCfgChildDao = new BeanHomeCfgChildDao(beanHomeCfgChildDaoConfig, this);
        beanHotGoodDao = new BeanHotGoodDao(beanHotGoodDaoConfig, this);
        beanLearningModuleDao = new BeanLearningModuleDao(beanLearningModuleDaoConfig, this);
        beanParentDao = new BeanParentDao(beanParentDaoConfig, this);
        beanStudentDao = new BeanStudentDao(beanStudentDaoConfig, this);
        beanTeacherDao = new BeanTeacherDao(beanTeacherDaoConfig, this);
        contactParentDao = new ContactParentDao(contactParentDaoConfig, this);
        contactSchoolDao = new ContactSchoolDao(contactSchoolDaoConfig, this);
        contactTeacherDao = new ContactTeacherDao(contactTeacherDaoConfig, this);

        registerDao(BeanBanner.class, beanBannerDao);
        registerDao(BeanClass.class, beanClassDao);
        registerDao(BeanCourse.class, beanCourseDao);
        registerDao(BeanHomeCfg.class, beanHomeCfgDao);
        registerDao(BeanHomeCfgChild.class, beanHomeCfgChildDao);
        registerDao(BeanHotGood.class, beanHotGoodDao);
        registerDao(BeanLearningModule.class, beanLearningModuleDao);
        registerDao(BeanParent.class, beanParentDao);
        registerDao(BeanStudent.class, beanStudentDao);
        registerDao(BeanTeacher.class, beanTeacherDao);
        registerDao(ContactParent.class, contactParentDao);
        registerDao(ContactSchool.class, contactSchoolDao);
        registerDao(ContactTeacher.class, contactTeacherDao);
    }
    
    public void clear() {
        beanBannerDaoConfig.getIdentityScope().clear();
        beanClassDaoConfig.getIdentityScope().clear();
        beanCourseDaoConfig.getIdentityScope().clear();
        beanHomeCfgDaoConfig.getIdentityScope().clear();
        beanHomeCfgChildDaoConfig.getIdentityScope().clear();
        beanHotGoodDaoConfig.getIdentityScope().clear();
        beanLearningModuleDaoConfig.getIdentityScope().clear();
        beanParentDaoConfig.getIdentityScope().clear();
        beanStudentDaoConfig.getIdentityScope().clear();
        beanTeacherDaoConfig.getIdentityScope().clear();
        contactParentDaoConfig.getIdentityScope().clear();
        contactSchoolDaoConfig.getIdentityScope().clear();
        contactTeacherDaoConfig.getIdentityScope().clear();
    }

    public BeanBannerDao getBeanBannerDao() {
        return beanBannerDao;
    }

    public BeanClassDao getBeanClassDao() {
        return beanClassDao;
    }

    public BeanCourseDao getBeanCourseDao() {
        return beanCourseDao;
    }

    public BeanHomeCfgDao getBeanHomeCfgDao() {
        return beanHomeCfgDao;
    }

    public BeanHomeCfgChildDao getBeanHomeCfgChildDao() {
        return beanHomeCfgChildDao;
    }

    public BeanHotGoodDao getBeanHotGoodDao() {
        return beanHotGoodDao;
    }

    public BeanLearningModuleDao getBeanLearningModuleDao() {
        return beanLearningModuleDao;
    }

    public BeanParentDao getBeanParentDao() {
        return beanParentDao;
    }

    public BeanStudentDao getBeanStudentDao() {
        return beanStudentDao;
    }

    public BeanTeacherDao getBeanTeacherDao() {
        return beanTeacherDao;
    }

    public ContactParentDao getContactParentDao() {
        return contactParentDao;
    }

    public ContactSchoolDao getContactSchoolDao() {
        return contactSchoolDao;
    }

    public ContactTeacherDao getContactTeacherDao() {
        return contactTeacherDao;
    }

}
