package com.hyphenate.easeui.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hyphenate.easeui.model.EaseLocalUser;

import com.hyphenate.easeui.model.EaseLocalUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig easeLocalUserDaoConfig;

    private final EaseLocalUserDao easeLocalUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        easeLocalUserDaoConfig = daoConfigMap.get(EaseLocalUserDao.class).clone();
        easeLocalUserDaoConfig.initIdentityScope(type);

        easeLocalUserDao = new EaseLocalUserDao(easeLocalUserDaoConfig, this);

        registerDao(EaseLocalUser.class, easeLocalUserDao);
    }
    
    public void clear() {
        easeLocalUserDaoConfig.getIdentityScope().clear();
    }

    public EaseLocalUserDao getEaseLocalUserDao() {
        return easeLocalUserDao;
    }

}
